version: '3.8'
networks:
  tmdb-net:

services:
  tmdb_db:
    container_name: tmdb_db
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tmdb
    networks:
      - tmdb-net
    volumes:
      - tmdb_db_vol:/var/lib/postgresql/data

volumes:
  tmdb_db_vol: {}

  # pg_admin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
  #     PGADMIN_DEFAULT_PASSWORD: 'admin'
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - tmdb_db
  #   networks:
  #     - tmdb-net

  # tmdb_api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: tmdb_api
  #   depends_on:
  #     - tmdb_db
  #   ports:
  #     - '3000:3000'
  #   restart: always
  #   networks:
  #     - tmdb-net
