version: '3.8'
services:
  tmdb_db:
    image: postgres:16.0-alpine3.18
    restart: always
    ports:
      - '9090:5432'
    expose:
      - 9090
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tmdb

  pg_admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '80:80'
    depends_on:
      - tmdb_db
